# Generated by Django 5.1.15 on 2026-04-27 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('hq_country', models.CharField(blank=True, max_length=2, null=True)),
                ('hq_city', models.CharField(blank=True, max_length=120, null=True)),
                ('industry', models.CharField(blank=True, max_length=120, null=True)),
                ('employee_band', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('LT_100', '< 100'), ('B_100_250', '100–250'), ('B_250_700', '250–700'), ('B_700_1000', '700–1,000'), ('GT_1000', '1,000+')], default='UNKNOWN', max_length=12)),
                ('cross_border_moves_band', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('LT_10', '< 10 / yr'), ('B_10_50', '10–50 / yr'), ('B_50_250', '50–250 / yr'), ('B_250_500', '250–500 / yr'), ('GT_500', '500+ / yr')], default='UNKNOWN', max_length=12)),
                ('countries_with_employees', models.JSONField(default=list)),
                ('current_tooling_tags', models.JSONField(default=list)),
                ('trigger_event', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NEW_MARKET', 'New market opened'), ('INTL_HIRING', 'International hiring'), ('AUDIT_FINDING', 'Audit / compliance finding'), ('OUTGREW_TOOL', 'Outgrew current tool'), ('RFP', 'RFP'), ('INBOUND', 'Inbound'), ('OTHER', 'Other')], default='UNKNOWN', max_length=20)),
                ('trigger_note', models.TextField(blank=True, null=True)),
                ('pursuit_status', models.CharField(choices=[('NEW', 'New'), ('RESEARCHING', 'Researching'), ('CONTACTING', 'Contacting'), ('ACTIVE_OPP', 'Active opportunity'), ('CUSTOMER', 'Customer'), ('DISQUALIFIED', 'Disqualified')], db_index=True, default='NEW', max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('ENRICHMENT', 'Auto-enrichment'), ('REFERRAL', 'Referral'), ('INBOUND', 'Inbound'), ('CONFERENCE', 'Conference'), ('IMPORT', 'Import')], db_index=True, default='MANUAL', max_length=12)),
                ('enrichment_confidence', models.FloatField(blank=True, null=True)),
                ('last_enriched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('NOTE', 'Note'), ('SYSTEM', 'System')], max_length=8)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('persona', models.CharField(choices=[('ECONOMIC_BUYER', 'Economic Buyer'), ('CHAMPION', 'Champion'), ('TECHNICAL', 'Technical Evaluator'), ('END_USER', 'End User'), ('EXEC_SPONSOR', 'Executive Sponsor'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_primary', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ENRICH', 'Enrich existing'), ('SOURCE', 'Source new')], db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=8)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fields_updated', models.JSONField(default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=80, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('PROSPECT', 'Prospect'), ('DISCOVERY', 'Discovery'), ('DEMO', 'Demo'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed won'), ('CLOSED_LOST', 'Closed lost'), ('ON_HOLD', 'On hold')], db_index=True, default='PROSPECT', max_length=14)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ['-updated_at'],
            },
        ),
    ]
